import os
import shutil
import subprocess
from fastapi import FastAPI, UploadFile, File, HTTPException
from fastapi.middleware.cors import CORSMiddleware

app = FastAPI(title="MediSync API")

# Enable CORS for frontend integration
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"], 
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Configuration & Paths
UPLOAD_DIR = "sri"
os.makedirs(UPLOAD_DIR, exist_ok=True)

@app.post("/record")
async def record_audio():
    """Execute sound.py script and return the generated summary."""
    try:
        print("🎤 Triggering sound.py...")
        # Using subprocess to execute the script in a blocked manner, capturing the output
        result = subprocess.run(
            ["python", "sound.py"], 
            capture_output=True, 
            text=True, 
            check=True
        )
        print("subprocess result:", result.stdout)

        # Read the summary file generated by sound.py
        summary_path = os.path.join(UPLOAD_DIR, "consulting_summary.txt")
        summary_content = ""
        if os.path.exists(summary_path):
            with open(summary_path, "r", encoding="utf-8") as f:
                summary_content = f.read()

        return {"message": "Recording processed successfully", "summary": summary_content, "log": result.stdout}
    except subprocess.CalledProcessError as e:
        print("❌ Error recording:", e.stderr)
        raise HTTPException(status_code=500, detail=f"Script error: {e.stderr}")
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@app.post("/upload")
async def upload_document(file: UploadFile = File(...)):
    """Upload documents to the sri directory."""
    try:
        file_path = os.path.join(UPLOAD_DIR, file.filename)
        with open(file_path, "wb") as buffer:
            shutil.copyfileobj(file.file, buffer)
        return {"filename": file.filename, "status": "Uploaded successfully"}
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@app.post("/sync")
async def sync_all():
    """Execute sync_all_send.py script to OCR and analyze."""
    try:
        print("🔄 Triggering sync_all_send.py...")
        # Run the script via subprocess and capture the standard output
        result = subprocess.run(
            ["python", "sync_all_send.py"], 
            capture_output=True, 
            text=True, 
            check=True
        )
        print("subprocess result:", result.stdout)
        
        # We can extract the final safety report if needed, or just return the entire stdout
        return {"status": "success", "message": "Synced and Report Sent via WhatsApp", "log": result.stdout}
    except subprocess.CalledProcessError as e:
        print("❌ Error syncing:", e.stderr)
        raise HTTPException(status_code=500, detail=f"Script error: {e.stderr}")
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)